package clicker.ventana;
import clicker.enemigos.Enemigo;
import java.util.Timer;
import java.util.TimerTask;


public class VentanaEnemigo extends javax.swing.JFrame {

    int s;
    Timer t;
    Enemigo enemigo;

    
    public VentanaEnemigo(Enemigo enemigo) {
        
        initComponents();
        setLocationRelativeTo(null);
        
        if("Virus".equals(enemigo.nombre())){
            getjLabel1().setIcon(new javax.swing.ImageIcon(getClass().getResource("/clicker/resources/FONDO VIRUS.jpg")));
        }
        
        if("Hacker".equals(enemigo.nombre())){
            getjLabel1().setIcon(new javax.swing.ImageIcon(getClass().getResource("/clicker/resources/FONDO HACKER.jpg")));
        }
        
        if("Invencible".equals(enemigo.nombre())){
            getjLabel1().setIcon(new javax.swing.ImageIcon(getClass().getResource("/clicker/resources/FONDO INVENCIBLE.jpg")));
        }
            
        setVisible(true);

        
        
        this.enemigo = enemigo;
        actualizarVida();  
        t = new Timer();
        t.schedule(accion, 0,100);
    }
    
    
    private TimerTask accion = new TimerTask(){

        @Override
       public void run() {
            s=enemigo.getTiempo();
            actualizarTiempo();
        }
        
    };
    
    
    private void actualizarTiempo() {
        String tiempo = "TIEMPO: " + (s<=9?"0":"")+s;
        textoTiempo.setText(tiempo);
        actualizarVida();
    }
    
    private void actualizarVida(){
        String tiempo = "VIDA: " + enemigo.getVida();
        textoVida.setText(tiempo);
    }
    
    /**Este metodo es muy importante, ya que elimina el hilo de TimerTask accion
     * de lo contrario este hilo seguira vivo a pesar de cerrarce la ventana
     */
    public void matar(){
        t.cancel();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonEnemigo = new javax.swing.JButton();
        textoTiempo = new javax.swing.JLabel();
        textoVida = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonEnemigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clicker/resources/BOTON DEFENSA.jpg"))); // NOI18N
        botonEnemigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEnemigoMouseClicked(evt);
            }
        });
        botonEnemigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnemigoActionPerformed(evt);
            }
        });
        getContentPane().add(botonEnemigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 163, 150, 75));

        textoTiempo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoTiempo.setForeground(new java.awt.Color(255, 255, 255));
        textoTiempo.setText("TIEMPO: 00 ");
        getContentPane().add(textoTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 130, 30));

        textoVida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoVida.setForeground(new java.awt.Color(255, 255, 255));
        textoVida.setText("VIDA:");
        getContentPane().add(textoVida, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 120, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEnemigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEnemigoMouseClicked
        enemigo.clcik();
        actualizarVida();
    }//GEN-LAST:event_botonEnemigoMouseClicked

    private void botonEnemigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnemigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEnemigoActionPerformed
    
    public javax.swing.JLabel getjLabel1(){
        return jLabel1;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEnemigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel textoTiempo;
    private javax.swing.JLabel textoVida;
    // End of variables declaration//GEN-END:variables
}
