/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clicker.ventana;

import clicker.ImagePanel;
import clicker.Juego;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Nehemias
 */
public class VentanaAumentarNivel extends javax.swing.JFrame {

    JFrame frame;
    Juego juego;

    /**
     * Creates new form VentanaAumentarNivel
     *
     * @param juego
     */
    public VentanaAumentarNivel(Juego juego) {
        initComponents();
        this.juego = juego;
        setLocationRelativeTo(null);
        setResizable(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    public void showGIF() throws MalformedURLException {
        frame = new JFrame("Image");
        frame.setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        frame.setUndecorated(true);
        frame.setSize(600, 400);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        frame.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        Integer nivel = this.juego.getNivel().getNumeroNivel();
        URL url;
        switch (nivel) {
            case 2:

                url = new URL("https://i.pinimg.com/originals/63/81/f6/6381f63592f18a7d91f9f3ac64009b42.gif");
                break;
            case 3:
                url = new URL("https://i.pinimg.com/originals/26/5f/1e/265f1e9da2dc2aafab154bdd6f64f2b9.gif");
                break;
            case 4:
                url = new URL("https://i.pinimg.com/originals/db/c6/59/dbc6597b27b388e63bb782875fc7140c.gif");

                break;
            case 5:
                url = new URL("https://cdn.eldeforma.com/wp-content/uploads/2020/03/giphy-5.gif");
                break;
            default:
                url = new URL("https://i.pinimg.com/originals/26/5f/1e/265f1e9da2dc2aafab154bdd6f64f2b9.gif");
                break;
        }

        //URL url = new URL("/clicker/resources/barcoBTC.gif");
        Image image = Toolkit.getDefaultToolkit().getImage(url);

        ImagePanel im = new ImagePanel(image);
        JLabel jlbl = new JLabel();

        jlbl.setText("¡Subiste al Nivel " + nivel.toString() + "!");
        String labelText = jlbl.getText();
        jlbl.setFont(new Font(labelText, Font.BOLD, 35));
        jlbl.setForeground(Color.white);
        im.add(jlbl);
        frame.add(im);
        frame.setVisible(true);
    }

    public void cerrarTodo() {
        frame.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VentanaAumentarNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VentanaAumentarNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VentanaAumentarNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VentanaAumentarNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VentanaAumentarNivel().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
