/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clicker.ventana;

import clicker.Juego;
import clicker.mejoras.*;

/**
 *
 * @author Nacho
 */
public class VentanaMejoras extends javax.swing.JFrame {
    
    private Juego juego;
    private MejoraActiva mejoraActiva;
    /**
     * Creates new form VentanaMejoras
     */
    public VentanaMejoras(Juego juego) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        this.juego = juego;
        
        this.mejoraActiva = new MejoraActiva(juego,1,this);       
        butDuplicator.setVisible(false);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        butDuplicator = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clicker/resources/VOLVER3.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 315, 150, 75));


        butDuplicator.setText("Duplicar monedas");
        butDuplicator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDuplicatorActionPerformed(evt);
            }
        });
        getContentPane().add(butDuplicator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));


        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clicker/resources/FONDO.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed


    private void butDuplicatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDuplicatorActionPerformed
        setVisible(false);
        mejoraActiva.mejora1();
    }//GEN-LAST:event_butDuplicatorActionPerformed


    public javax.swing.JButton getBoton1(){
        return jButton1;
    }
    
    public javax.swing.JLabel getLabel1(){
        return jLabel1;
    }

    public javax.swing.JButton getButDuplicator(){
        return butDuplicator;
    }


    // Variables declaration - do not modify                     
    private javax.swing.JButton butDuplicator;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration
}
